nameNormalize = {
    "longitude": "longitude",
    "latitude": "latitude",
    "zipcode": "zipcode",
    "zip": "zipcode",
    "street": "address",
    "block": "address",
    "address": "address",
    "location": "other location attribute",
    "city": "city",
    "state": "state",
    "country": "country",
    "borough": "borough",
    "tax_block": "other location attribute",
    "tax_lot": "other location attribute",
    "bin": "other location attribute",
    "bbl": "other location attribute",
    "nta": "other location attribute",
    "lot": "other location attribute",
    "community_board": "other location attribute",
    "council_district": "other location attribute",
    "council_distrcit": "other location attribute",
    "community_district": "other location attribute",
    "census_tract": "other location attribute",
    "precinct": "other location attribute",
    "census_board": "other location attribute",
    "geom": "other location attribute",
    "other": "other location attribute",
    "county": "other location attribute",
    "n/a": "not spatial attribute"
}
types = ["longitude", "latitude", "address", "borough", "city", "state",
                      "country",  "zipcode",
                      "other location attribute",
                      "not spatial attribute"]